In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'e:\\MCPWITHLANGCHAIN\\01_mcp_langchain\\mlops\\notebooks'

In [11]:
data_dir= os.path.join("..", "data", "experimental")
print(os.path.exists(data_dir))

# filepath & read dataset
filepath= os.path.join(data_dir, "data.csv")
df= pd.read_csv(filepath)
df.head()

True

                                              review sentiment
0  Now I love Bela Lugosi,don't get me wrong,he i...  negative
1  Routine suspense yarn about a sociopath (Dillo...  negative
2  1st watched 5/17/2002 - 3 out of 10(Dir-Ewald ...  negative
3  "Most of us at least inhabit two worlds , the ...  positive
4  Excellent performance. There still are good ac...  positive

In [12]:
df.shape

(500, 2)

In [16]:
updated_data= df.iloc[:400]
updated_data

                                                review sentiment
0    Now I love Bela Lugosi,don't get me wrong,he i...  negative
1    Routine suspense yarn about a sociopath (Dillo...  negative
2    1st watched 5/17/2002 - 3 out of 10(Dir-Ewald ...  negative
3    "Most of us at least inhabit two worlds , the ...  positive
4    Excellent performance. There still are good ac...  positive
..                                                 ...       ...
395  This reminds me of when I was a born-again bel...  negative
396  Oh my lord, what were they thinking about with...  negative
397  not a Larry Mcmurty masterpiece but it stands ...  positive
398  Wonderful family film that should be a staple ...  positive
399  I want to state first that I am a Christian (a...  negative

[400 rows x 2 columns]

In [17]:
updated_data.to_csv(filepath)

# Command Summary
```bash
git init
dvc init
cp ../data/experimental/data.csv .
dvc add data.csv
git add data.csv.dvc .gitignore
git commit -m "Initial version"

# Change 1
echo "new_value,999" >> data.csv
dvc add data.csv && git add data.csv.dvc
git commit -m "Added new row"

# Change 2
# (Remove row using shell commands)
dvc add data.csv && git add data.csv.dvc
git commit -m "Removed row"

# Revert
git checkout <initial_commit_hash>
dvc checkout

# check the commit history
git log 

```

# 1) now load the changed data

In [18]:
data_dir= os.path.join("..", "data", "experimental")
print(os.path.exists(data_dir))

# filepath & read dataset
filepath= os.path.join(data_dir, "data.csv")
df= pd.read_csv(filepath)
df.head(), df.shape

True

(   Unnamed: 0                                             review sentiment
 0           0  Now I love Bela Lugosi,don't get me wrong,he i...  negative
 1           1  Routine suspense yarn about a sociopath (Dillo...  negative
 2           2  1st watched 5/17/2002 - 3 out of 10(Dir-Ewald ...  negative
 3           3  "Most of us at least inhabit two worlds , the ...  positive
 4           4  Excellent performance. There still are good ac...  positive,
 (400, 3))

# after reverting

-- Now you can see I have 500 Records

In [20]:
data_dir= os.path.join("..", "data", "experimental")
print(os.path.exists(data_dir))

# filepath & read dataset
filepath= os.path.join(data_dir, "data.csv")
df= pd.read_csv(filepath)
df.head(), df.shape

True

(                                              review sentiment
 0  Now I love Bela Lugosi,don't get me wrong,he i...  negative
 1  Routine suspense yarn about a sociopath (Dillo...  negative
 2  1st watched 5/17/2002 - 3 out of 10(Dir-Ewald ...  negative
 3  "Most of us at least inhabit two worlds , the ...  positive
 4  Excellent performance. There still are good ac...  positive,
 (500, 2))

# After move to the main branch

```bash
$ git checkout main
$ dvc checkout
```

In [22]:
data_dir= os.path.join("..", "data", "experimental")
print(os.path.exists(data_dir))

# filepath & read dataset
filepath= os.path.join(data_dir, "data.csv")
df= pd.read_csv(filepath)
df.head(), df.shape

True

(   Unnamed: 0                                             review sentiment
 0           0  Now I love Bela Lugosi,don't get me wrong,he i...  negative
 1           1  Routine suspense yarn about a sociopath (Dillo...  negative
 2           2  1st watched 5/17/2002 - 3 out of 10(Dir-Ewald ...  negative
 3           3  "Most of us at least inhabit two worlds , the ...  positive
 4           4  Excellent performance. There still are good ac...  positive,
 (400, 3))

## rough work

In [26]:
import pandas as pd
data_url= 'https://raw.githubusercontent.com/shubhamchau222/mlops-pipeline/refs/heads/main/raw_data/data.csv'
df = pd.read_csv(data_url)
df.head()

                                              review sentiment
0  Now I love Bela Lugosi,don't get me wrong,he i...  negative
1  Routine suspense yarn about a sociopath (Dillo...  negative
2  1st watched 5/17/2002 - 3 out of 10(Dir-Ewald ...  negative
3  "Most of us at least inhabit two worlds , the ...  positive
4  Excellent performance. There still are good ac...  positive